'use client';
import { useEffect } from 'react';
import { flushSync } from 'react-dom';
export type Scenario={members:number;cohort:number;pmpm:number;information:number;acceleration:number};
export const limits={members:500000,cohort:100,pmpm:150,information:100,acceleration:100};
export function calculate(s:Scenario){const gap=s.members*s.cohort/100*s.pmpm*12;const information=gap*s.information/100;return {annual_cohort_gap:gap,assumed_information_component:information,annualized_gross_opportunity:information*s.acceleration/100,currency:'USD',note:'Illustrative scenario before costs, not a forecast.'}}
export function validateScenario(input:unknown):Scenario{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('A scenario object is required.');const v=input as Record<string,unknown>;if(Object.keys(v).length!==5)throw new Error('Exactly five scenario inputs are required.');for(const [key,max]of Object.entries(limits)){if(typeof v[key]!=='number'||!Number.isInteger(v[key])||(v[key] as number)<0||(v[key] as number)>max)throw new Error(`${key} must be an integer from 0 to ${max}.`)}return v as Scenario}
type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type AgentDocument=Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}};
export function useScenarioTool(setScenario:(s:Scenario)=>void){useEffect(()=>{const context=(document as AgentDocument).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'update_business_scenario',description:'Set all five visible business-case sliders and return the illustrative annualized arithmetic before costs. Changes this page only.',inputSchema:{type:'object',properties:Object.fromEntries(Object.entries(limits).map(([k,max])=>[k,{type:'integer',minimum:0,maximum:max}])),required:Object.keys(limits),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const s=validateScenario(input);flushSync(()=>setScenario(s));return calculate(s)}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser API; ordinary controls remain available. */}return()=>lifecycle.abort()},[setScenario])}
