'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, ArrowRight, RotateCcw } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Experiment, Architecture, EvaluationSection, AuditSection, Limitations } from './experiment';
import { useScenarioTool } from './agent-tools';
const defaults = { members:157309, cohort:28, pmpm:70, information:33, acceleration:50 };
const currency = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:1,notation:'compact'}).format(n);
const source = 'https://investors.cloverhealth.com/static-files/8940df35-b935-4f1d-b6e6-d931c1b7f885';
export default function Home() {
 const [inputs,setInputs]=useState(defaults);
 useScenarioTool(setInputs);
 const gap=inputs.members*inputs.cohort/100*inputs.pmpm*12;
 const information=gap*inputs.information/100;
 const opportunity=information*inputs.acceleration/100;
 const fields = [
  {key:'members',label:'Members',min:0,max:500000,step:1,value:inputs.members.toLocaleString(),note:'Public reference · June 30, 2026'},
  {key:'cohort',label:'First-year cohort share',min:0,max:100,step:1,value:inputs.cohort+'%',note:'Assumption · share of all members'},
  {key:'pmpm',label:'Year 1 → 2 improvement',min:0,max:150,step:1,value:'$'+inputs.pmpm+' PMPM',note:'Management commentary · gross profit'},
  {key:'information',label:'Share driven by information',min:0,max:100,step:1,value:inputs.information+'%',note:'Assumption · decomposition unknown'},
  {key:'acceleration',label:'Share brought forward',min:0,max:100,step:1,value:inputs.acceleration+'%',note:'Assumption · requires evidence of effect'},
 ] as const;
 return <>
  <a className="skip-link" href="#business-case">Skip to calculator</a>
  <header className="masthead"><a href="#" className="wordmark">DAY ONE<span className="brand-dot" /></a><span className="header-note">An independent proposal for Clover Health /COMMIT</span><nav><a href="#business-case">The case</a><a href="#demo">The prototype <ArrowUpRight size={14}/></a></nav></header>
  <main>
   <section className="hero wrap"><div className="eyebrow"><span className="edition">RESEARCH MEMO 001</span><span>SEPTEMBER 2026</span></div><div className="hero-grid"><div><h1>A better first visit<br/>starts with a<br/><em>better record.</em></h1><p className="hero-deck">Could earlier information bring part of Clover’s cohort curve forward? A working, synthetic prototype to make that question concrete.</p><div className="hero-actions"><a className="button primary" href="#business-case">Explore the business case <ArrowDown size={16}/></a><a className="text-link" href="#demo">See it run <ArrowUpRight size={16}/></a></div></div><aside className="hero-note"><span className="eyebrow">THE QUESTION</span><div className="hero-number">$70<span>/ member / month</span></div><p>Typical gross-profit improvement from a cohort’s first year to its second, according to management.</p><a className="source-link" href={source} target="_blank" rel="noreferrer">Q2 2026 earnings call, p. 3 <ArrowUpRight size={13}/></a><div className="hypothesis">Some of that gap may be an information gap.<br/><strong>How much is still an open question.</strong></div></aside></div><div className="byline"><span>Rahul Chowdary Vajja</span><span>Independent proposal · All data synthetic · No affiliation or endorsement</span></div></section>
   <section className="section wrap" id="observation"><div className="section-heading"><span className="section-number">01 / THE OBSERVATION</span><h2>The curve is real.<br/>The explanation is incomplete.</h2></div><div className="observation-grid"><div><p className="lead">A new member brings a history.<br/>The first visit may see only a fraction of it.</p><p>Management describes roughly $70 PMPM of typical gross-profit improvement between year one and year two. Identification, intervention, care management, and time for physicians to act all contribute. Public disclosures do not isolate the information component.</p><a className="source-link" href={source} target="_blank" rel="noreferrer">Management’s commentary <ArrowUpRight size={13}/></a></div><div className="record-diagram" aria-label="Conceptual diagram: earlier record assembly could bring information to the first visit"><div><span className="eyebrow">YEAR ONE</span><h3>History in fragments</h3><div className="record-bars"><i/><i/><i className="missing"/><i className="missing"/></div><span className="small muted">Unknowns and disconnected records</span></div><ArrowRight className="diagram-arrow" size={24}/><div><span className="eyebrow">THE OPPORTUNITY</span><h3>Context, sooner</h3><div className="record-bars complete"><i/><i/><i/><i/></div><span className="small muted">A cited brief for clinician review</span></div><p className="diagram-caption">Conceptual illustration. Earlier information does not guarantee earlier benefit.</p></div></div><div className="rail-note"><span className="rail-label">WHY NOW</span><p>Clover announced patient-directed clinical and claims exchange through <a href="https://investors.cloverhealth.com/news-releases/news-release-details/updated-moving-pledge-production-clover-health-now-live-kno2/" target="_blank" rel="noreferrer">Kno2 in March 2026</a> and is listed as a <a href="https://www.cms.gov/initiatives/health-technology-ecosystem/overview/early-adopters-all-pledgees/payers-their-delegated-technology" target="_blank" rel="noreferrer">CMS interoperability pledgee</a>. These are relevant rails; inbound record coverage and access at enrollment still need to be established.</p></div></section>
   <section className="section case-section" id="business-case"><div className="wrap"><div className="section-heading"><span className="section-number">02 / THE BUSINESS CASE</span><div><h2>Disagree with the assumptions.<br/>Move the numbers.</h2><p className="section-deck">An adjustable scenario, built on two public reference points.</p></div></div><div className="calculator"><div className="controls"><div className="controls-top"><span className="eyebrow">MODEL INPUTS</span><button className="reset" onClick={()=>setInputs(defaults)}><RotateCcw size={14}/> Reset</button></div>{fields.map(f=><div className="control" key={f.key}><div className="control-label"><label id={'label-'+f.key}>{f.label}</label><output>{f.value}</output></div><Slider aria-labelledby={'label-'+f.key} value={[inputs[f.key]]} min={f.min} max={f.max} step={f.step} onValueChange={v=>setInputs(s=>({...s,[f.key]:Array.isArray(v)?v[0]:v}))}/><p className="small muted">{f.note}</p></div>)}</div><div className="calculation" aria-live="polite" aria-atomic="true"><span className="eyebrow">ILLUSTRATIVE ANNUALIZED OPPORTUNITY</span><div className="opportunity">{currency(opportunity)}</div><p className="result-note">Gross scenario value, before costs.<br/>Not a forecast of realized savings.</p><div className="waterfall"><div><span>Modeled annual cohort gap</span><strong>{currency(gap)}</strong></div><div><span>Assumed information component <small>× {inputs.information}%</small></span><strong>{currency(information)}</strong></div><div className="final-row"><span>Assumed share brought forward <small>× {inputs.acceleration}%</small></span><strong>{currency(opportunity)}</strong></div></div><div className="formula"><span className="eyebrow">THE ARITHMETIC</span><p>{inputs.members.toLocaleString()} members × {inputs.cohort}% cohort × ${inputs.pmpm} × 12 months × {inputs.information}% × {inputs.acceleration}%</p></div></div></div><p className="assumptions"><strong>These are my assumptions, not Clover projections.</strong> The input that decides the answer is Clover’s own decomposition of year one to year two, which I do not have. Coverage, uptake, retention, implementation costs, and causal effects are not modeled. <a href="https://www.sec.gov/Archives/edgar/data/1801170/000180117026000196/a2q26exx991xearningsrelease.htm" target="_blank" rel="noreferrer">157,309 is quarter-end membership</a>; the cohort share is an assumption. Set either information assumption to zero to model no benefit.</p></div></section>
   <Experiment/><Architecture/><EvaluationSection/><AuditSection/><Limitations/>
  </main><footer className="wrap footer"><span className="wordmark">DAY ONE<span className="brand-dot"/></span><p>Rahul Chowdary Vajja · All data synthetic</p><a className="text-link" href="https://github.com/vajja1405/day-one" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><a className="text-link" href="https://github.com/vajja1405/day-one/archive/refs/heads/main.zip" download>Download the source <ArrowDown size={14}/></a></footer><span className="persistent-synthetic">SYNTHETIC DATA · INDEPENDENT PROTOTYPE</span>
 </>;
}
